# ref: https://hub.docker.com/_/mysql
version: '3.7'

services:

  mysql:  ## Use root/root as user/password MySQL credentials
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "${SCHEMA_DIR}:/opt"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:3306:3306

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
