// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type DeptManager struct {
	ent.Schema
}

func (DeptManager) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("employee_id").Optional(), field.String("department_id").Optional(), field.Time("from_date"), field.Time("to_date"), field.Time("created_at").Optional(), field.Time("updated_at").Optional()}
}
func (DeptManager) Edges() []ent.Edge {
	return []ent.Edge{edge.From("employee", Employee.Type).Ref("dept_managers").Unique().Field("employee_id"), edge.From("department", Department.Type).Ref("dept_managers").Unique().Field("department_id")}
}
func (DeptManager) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "dept_manager"}}
}
