// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"employees/ent/deptemployee"
	"employees/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeptEmployeeDelete is the builder for deleting a DeptEmployee entity.
type DeptEmployeeDelete struct {
	config
	hooks    []Hook
	mutation *DeptEmployeeMutation
}

// Where appends a list predicates to the DeptEmployeeDelete builder.
func (ded *DeptEmployeeDelete) Where(ps ...predicate.DeptEmployee) *DeptEmployeeDelete {
	ded.mutation.Where(ps...)
	return ded
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ded *DeptEmployeeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ded.sqlExec, ded.mutation, ded.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ded *DeptEmployeeDelete) ExecX(ctx context.Context) int {
	n, err := ded.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ded *DeptEmployeeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(deptemployee.Table, sqlgraph.NewFieldSpec(deptemployee.FieldID, field.TypeString))
	if ps := ded.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ded.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ded.mutation.done = true
	return affected, err
}

// DeptEmployeeDeleteOne is the builder for deleting a single DeptEmployee entity.
type DeptEmployeeDeleteOne struct {
	ded *DeptEmployeeDelete
}

// Where appends a list predicates to the DeptEmployeeDelete builder.
func (dedo *DeptEmployeeDeleteOne) Where(ps ...predicate.DeptEmployee) *DeptEmployeeDeleteOne {
	dedo.ded.mutation.Where(ps...)
	return dedo
}

// Exec executes the deletion query.
func (dedo *DeptEmployeeDeleteOne) Exec(ctx context.Context) error {
	n, err := dedo.ded.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{deptemployee.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dedo *DeptEmployeeDeleteOne) ExecX(ctx context.Context) {
	if err := dedo.Exec(ctx); err != nil {
		panic(err)
	}
}
