// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"employees/ent/department"
	"employees/ent/deptemployee"
	"employees/ent/employee"
	"employees/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeptEmployeeQuery is the builder for querying DeptEmployee entities.
type DeptEmployeeQuery struct {
	config
	ctx            *QueryContext
	order          []deptemployee.OrderOption
	inters         []Interceptor
	predicates     []predicate.DeptEmployee
	withEmployee   *EmployeeQuery
	withDepartment *DepartmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeptEmployeeQuery builder.
func (deq *DeptEmployeeQuery) Where(ps ...predicate.DeptEmployee) *DeptEmployeeQuery {
	deq.predicates = append(deq.predicates, ps...)
	return deq
}

// Limit the number of records to be returned by this query.
func (deq *DeptEmployeeQuery) Limit(limit int) *DeptEmployeeQuery {
	deq.ctx.Limit = &limit
	return deq
}

// Offset to start from.
func (deq *DeptEmployeeQuery) Offset(offset int) *DeptEmployeeQuery {
	deq.ctx.Offset = &offset
	return deq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (deq *DeptEmployeeQuery) Unique(unique bool) *DeptEmployeeQuery {
	deq.ctx.Unique = &unique
	return deq
}

// Order specifies how the records should be ordered.
func (deq *DeptEmployeeQuery) Order(o ...deptemployee.OrderOption) *DeptEmployeeQuery {
	deq.order = append(deq.order, o...)
	return deq
}

// QueryEmployee chains the current query on the "employee" edge.
func (deq *DeptEmployeeQuery) QueryEmployee() *EmployeeQuery {
	query := (&EmployeeClient{config: deq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := deq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := deq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deptemployee.Table, deptemployee.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deptemployee.EmployeeTable, deptemployee.EmployeeColumn),
		)
		fromU = sqlgraph.SetNeighbors(deq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDepartment chains the current query on the "department" edge.
func (deq *DeptEmployeeQuery) QueryDepartment() *DepartmentQuery {
	query := (&DepartmentClient{config: deq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := deq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := deq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deptemployee.Table, deptemployee.FieldID, selector),
			sqlgraph.To(department.Table, department.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deptemployee.DepartmentTable, deptemployee.DepartmentColumn),
		)
		fromU = sqlgraph.SetNeighbors(deq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeptEmployee entity from the query.
// Returns a *NotFoundError when no DeptEmployee was found.
func (deq *DeptEmployeeQuery) First(ctx context.Context) (*DeptEmployee, error) {
	nodes, err := deq.Limit(1).All(setContextOp(ctx, deq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deptemployee.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (deq *DeptEmployeeQuery) FirstX(ctx context.Context) *DeptEmployee {
	node, err := deq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeptEmployee ID from the query.
// Returns a *NotFoundError when no DeptEmployee ID was found.
func (deq *DeptEmployeeQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = deq.Limit(1).IDs(setContextOp(ctx, deq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deptemployee.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (deq *DeptEmployeeQuery) FirstIDX(ctx context.Context) string {
	id, err := deq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeptEmployee entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeptEmployee entity is found.
// Returns a *NotFoundError when no DeptEmployee entities are found.
func (deq *DeptEmployeeQuery) Only(ctx context.Context) (*DeptEmployee, error) {
	nodes, err := deq.Limit(2).All(setContextOp(ctx, deq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deptemployee.Label}
	default:
		return nil, &NotSingularError{deptemployee.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (deq *DeptEmployeeQuery) OnlyX(ctx context.Context) *DeptEmployee {
	node, err := deq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeptEmployee ID in the query.
// Returns a *NotSingularError when more than one DeptEmployee ID is found.
// Returns a *NotFoundError when no entities are found.
func (deq *DeptEmployeeQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = deq.Limit(2).IDs(setContextOp(ctx, deq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deptemployee.Label}
	default:
		err = &NotSingularError{deptemployee.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (deq *DeptEmployeeQuery) OnlyIDX(ctx context.Context) string {
	id, err := deq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeptEmployees.
func (deq *DeptEmployeeQuery) All(ctx context.Context) ([]*DeptEmployee, error) {
	ctx = setContextOp(ctx, deq.ctx, "All")
	if err := deq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeptEmployee, *DeptEmployeeQuery]()
	return withInterceptors[[]*DeptEmployee](ctx, deq, qr, deq.inters)
}

// AllX is like All, but panics if an error occurs.
func (deq *DeptEmployeeQuery) AllX(ctx context.Context) []*DeptEmployee {
	nodes, err := deq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeptEmployee IDs.
func (deq *DeptEmployeeQuery) IDs(ctx context.Context) (ids []string, err error) {
	if deq.ctx.Unique == nil && deq.path != nil {
		deq.Unique(true)
	}
	ctx = setContextOp(ctx, deq.ctx, "IDs")
	if err = deq.Select(deptemployee.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (deq *DeptEmployeeQuery) IDsX(ctx context.Context) []string {
	ids, err := deq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (deq *DeptEmployeeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, deq.ctx, "Count")
	if err := deq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, deq, querierCount[*DeptEmployeeQuery](), deq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (deq *DeptEmployeeQuery) CountX(ctx context.Context) int {
	count, err := deq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (deq *DeptEmployeeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, deq.ctx, "Exist")
	switch _, err := deq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (deq *DeptEmployeeQuery) ExistX(ctx context.Context) bool {
	exist, err := deq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeptEmployeeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (deq *DeptEmployeeQuery) Clone() *DeptEmployeeQuery {
	if deq == nil {
		return nil
	}
	return &DeptEmployeeQuery{
		config:         deq.config,
		ctx:            deq.ctx.Clone(),
		order:          append([]deptemployee.OrderOption{}, deq.order...),
		inters:         append([]Interceptor{}, deq.inters...),
		predicates:     append([]predicate.DeptEmployee{}, deq.predicates...),
		withEmployee:   deq.withEmployee.Clone(),
		withDepartment: deq.withDepartment.Clone(),
		// clone intermediate query.
		sql:  deq.sql.Clone(),
		path: deq.path,
	}
}

// WithEmployee tells the query-builder to eager-load the nodes that are connected to
// the "employee" edge. The optional arguments are used to configure the query builder of the edge.
func (deq *DeptEmployeeQuery) WithEmployee(opts ...func(*EmployeeQuery)) *DeptEmployeeQuery {
	query := (&EmployeeClient{config: deq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	deq.withEmployee = query
	return deq
}

// WithDepartment tells the query-builder to eager-load the nodes that are connected to
// the "department" edge. The optional arguments are used to configure the query builder of the edge.
func (deq *DeptEmployeeQuery) WithDepartment(opts ...func(*DepartmentQuery)) *DeptEmployeeQuery {
	query := (&DepartmentClient{config: deq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	deq.withDepartment = query
	return deq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EmployeeID string `json:"employee_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeptEmployee.Query().
//		GroupBy(deptemployee.FieldEmployeeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (deq *DeptEmployeeQuery) GroupBy(field string, fields ...string) *DeptEmployeeGroupBy {
	deq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeptEmployeeGroupBy{build: deq}
	grbuild.flds = &deq.ctx.Fields
	grbuild.label = deptemployee.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EmployeeID string `json:"employee_id,omitempty"`
//	}
//
//	client.DeptEmployee.Query().
//		Select(deptemployee.FieldEmployeeID).
//		Scan(ctx, &v)
func (deq *DeptEmployeeQuery) Select(fields ...string) *DeptEmployeeSelect {
	deq.ctx.Fields = append(deq.ctx.Fields, fields...)
	sbuild := &DeptEmployeeSelect{DeptEmployeeQuery: deq}
	sbuild.label = deptemployee.Label
	sbuild.flds, sbuild.scan = &deq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeptEmployeeSelect configured with the given aggregations.
func (deq *DeptEmployeeQuery) Aggregate(fns ...AggregateFunc) *DeptEmployeeSelect {
	return deq.Select().Aggregate(fns...)
}

func (deq *DeptEmployeeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range deq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, deq); err != nil {
				return err
			}
		}
	}
	for _, f := range deq.ctx.Fields {
		if !deptemployee.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if deq.path != nil {
		prev, err := deq.path(ctx)
		if err != nil {
			return err
		}
		deq.sql = prev
	}
	return nil
}

func (deq *DeptEmployeeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeptEmployee, error) {
	var (
		nodes       = []*DeptEmployee{}
		_spec       = deq.querySpec()
		loadedTypes = [2]bool{
			deq.withEmployee != nil,
			deq.withDepartment != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeptEmployee).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeptEmployee{config: deq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, deq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := deq.withEmployee; query != nil {
		if err := deq.loadEmployee(ctx, query, nodes, nil,
			func(n *DeptEmployee, e *Employee) { n.Edges.Employee = e }); err != nil {
			return nil, err
		}
	}
	if query := deq.withDepartment; query != nil {
		if err := deq.loadDepartment(ctx, query, nodes, nil,
			func(n *DeptEmployee, e *Department) { n.Edges.Department = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (deq *DeptEmployeeQuery) loadEmployee(ctx context.Context, query *EmployeeQuery, nodes []*DeptEmployee, init func(*DeptEmployee), assign func(*DeptEmployee, *Employee)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*DeptEmployee)
	for i := range nodes {
		fk := nodes[i].EmployeeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(employee.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "employee_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (deq *DeptEmployeeQuery) loadDepartment(ctx context.Context, query *DepartmentQuery, nodes []*DeptEmployee, init func(*DeptEmployee), assign func(*DeptEmployee, *Department)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*DeptEmployee)
	for i := range nodes {
		fk := nodes[i].DepartmentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(department.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "department_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (deq *DeptEmployeeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := deq.querySpec()
	_spec.Node.Columns = deq.ctx.Fields
	if len(deq.ctx.Fields) > 0 {
		_spec.Unique = deq.ctx.Unique != nil && *deq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, deq.driver, _spec)
}

func (deq *DeptEmployeeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deptemployee.Table, deptemployee.Columns, sqlgraph.NewFieldSpec(deptemployee.FieldID, field.TypeString))
	_spec.From = deq.sql
	if unique := deq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if deq.path != nil {
		_spec.Unique = true
	}
	if fields := deq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deptemployee.FieldID)
		for i := range fields {
			if fields[i] != deptemployee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if deq.withEmployee != nil {
			_spec.Node.AddColumnOnce(deptemployee.FieldEmployeeID)
		}
		if deq.withDepartment != nil {
			_spec.Node.AddColumnOnce(deptemployee.FieldDepartmentID)
		}
	}
	if ps := deq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := deq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := deq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := deq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (deq *DeptEmployeeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(deq.driver.Dialect())
	t1 := builder.Table(deptemployee.Table)
	columns := deq.ctx.Fields
	if len(columns) == 0 {
		columns = deptemployee.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if deq.sql != nil {
		selector = deq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if deq.ctx.Unique != nil && *deq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range deq.predicates {
		p(selector)
	}
	for _, p := range deq.order {
		p(selector)
	}
	if offset := deq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := deq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeptEmployeeGroupBy is the group-by builder for DeptEmployee entities.
type DeptEmployeeGroupBy struct {
	selector
	build *DeptEmployeeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (degb *DeptEmployeeGroupBy) Aggregate(fns ...AggregateFunc) *DeptEmployeeGroupBy {
	degb.fns = append(degb.fns, fns...)
	return degb
}

// Scan applies the selector query and scans the result into the given value.
func (degb *DeptEmployeeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, degb.build.ctx, "GroupBy")
	if err := degb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeptEmployeeQuery, *DeptEmployeeGroupBy](ctx, degb.build, degb, degb.build.inters, v)
}

func (degb *DeptEmployeeGroupBy) sqlScan(ctx context.Context, root *DeptEmployeeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(degb.fns))
	for _, fn := range degb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*degb.flds)+len(degb.fns))
		for _, f := range *degb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*degb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := degb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeptEmployeeSelect is the builder for selecting fields of DeptEmployee entities.
type DeptEmployeeSelect struct {
	*DeptEmployeeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (des *DeptEmployeeSelect) Aggregate(fns ...AggregateFunc) *DeptEmployeeSelect {
	des.fns = append(des.fns, fns...)
	return des
}

// Scan applies the selector query and scans the result into the given value.
func (des *DeptEmployeeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, des.ctx, "Select")
	if err := des.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeptEmployeeQuery, *DeptEmployeeSelect](ctx, des.DeptEmployeeQuery, des, des.inters, v)
}

func (des *DeptEmployeeSelect) sqlScan(ctx context.Context, root *DeptEmployeeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(des.fns))
	for _, fn := range des.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*des.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := des.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
