// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"employees/ent/employee"
	"employees/ent/salary"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SalaryCreate is the builder for creating a Salary entity.
type SalaryCreate struct {
	config
	mutation *SalaryMutation
	hooks    []Hook
}

// SetEmployeeID sets the "employee_id" field.
func (sc *SalaryCreate) SetEmployeeID(s string) *SalaryCreate {
	sc.mutation.SetEmployeeID(s)
	return sc
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (sc *SalaryCreate) SetNillableEmployeeID(s *string) *SalaryCreate {
	if s != nil {
		sc.SetEmployeeID(*s)
	}
	return sc
}

// SetSalary sets the "salary" field.
func (sc *SalaryCreate) SetSalary(i int32) *SalaryCreate {
	sc.mutation.SetSalary(i)
	return sc
}

// SetFromDate sets the "from_date" field.
func (sc *SalaryCreate) SetFromDate(t time.Time) *SalaryCreate {
	sc.mutation.SetFromDate(t)
	return sc
}

// SetToDate sets the "to_date" field.
func (sc *SalaryCreate) SetToDate(t time.Time) *SalaryCreate {
	sc.mutation.SetToDate(t)
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SalaryCreate) SetCreatedAt(t time.Time) *SalaryCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SalaryCreate) SetNillableCreatedAt(t *time.Time) *SalaryCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *SalaryCreate) SetUpdatedAt(t time.Time) *SalaryCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *SalaryCreate) SetNillableUpdatedAt(t *time.Time) *SalaryCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *SalaryCreate) SetID(s string) *SalaryCreate {
	sc.mutation.SetID(s)
	return sc
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (sc *SalaryCreate) SetEmployee(e *Employee) *SalaryCreate {
	return sc.SetEmployeeID(e.ID)
}

// Mutation returns the SalaryMutation object of the builder.
func (sc *SalaryCreate) Mutation() *SalaryMutation {
	return sc.mutation
}

// Save creates the Salary in the database.
func (sc *SalaryCreate) Save(ctx context.Context) (*Salary, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SalaryCreate) SaveX(ctx context.Context) *Salary {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SalaryCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SalaryCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SalaryCreate) check() error {
	if _, ok := sc.mutation.Salary(); !ok {
		return &ValidationError{Name: "salary", err: errors.New(`ent: missing required field "Salary.salary"`)}
	}
	if _, ok := sc.mutation.FromDate(); !ok {
		return &ValidationError{Name: "from_date", err: errors.New(`ent: missing required field "Salary.from_date"`)}
	}
	if _, ok := sc.mutation.ToDate(); !ok {
		return &ValidationError{Name: "to_date", err: errors.New(`ent: missing required field "Salary.to_date"`)}
	}
	return nil
}

func (sc *SalaryCreate) sqlSave(ctx context.Context) (*Salary, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Salary.ID type: %T", _spec.ID.Value)
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SalaryCreate) createSpec() (*Salary, *sqlgraph.CreateSpec) {
	var (
		_node = &Salary{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(salary.Table, sqlgraph.NewFieldSpec(salary.FieldID, field.TypeString))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.Salary(); ok {
		_spec.SetField(salary.FieldSalary, field.TypeInt32, value)
		_node.Salary = value
	}
	if value, ok := sc.mutation.FromDate(); ok {
		_spec.SetField(salary.FieldFromDate, field.TypeTime, value)
		_node.FromDate = value
	}
	if value, ok := sc.mutation.ToDate(); ok {
		_spec.SetField(salary.FieldToDate, field.TypeTime, value)
		_node.ToDate = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(salary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(salary.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := sc.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   salary.EmployeeTable,
			Columns: []string{salary.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmployeeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SalaryCreateBulk is the builder for creating many Salary entities in bulk.
type SalaryCreateBulk struct {
	config
	err      error
	builders []*SalaryCreate
}

// Save creates the Salary entities in the database.
func (scb *SalaryCreateBulk) Save(ctx context.Context) ([]*Salary, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Salary, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SalaryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SalaryCreateBulk) SaveX(ctx context.Context) []*Salary {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SalaryCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SalaryCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
